### ISSUE TITLE
无效

### ISSUE THREAD

**Issue by weiyouren** [linglongxin24/DylanStepCount#1]
我在华为荣耀5c上安装，永远0步，不计步。需要什么硬件要求吗

**Comment by linglongxin24** [comment]
这个需要硬件支持，你看看硬件是否支持，或者你给我截图下你运行app的首页？

**Comment by weiyouren** [comment]
![screenshot_2016-10-24-09-49-00](https://cloud.githubusercontent.com/assets/3372167/19631463/3f656806-99cf-11e6-9e47-c837d83c3dc9.png)
![screenshot_2016-10-24-09-48-35](https://cloud.githubusercontent.com/assets/3372167/19631464/3f6c240c-99cf-11e6-9fca-37f85e7d7e25.png)

**Comment by linglongxin24** [comment]
你点击允许了么？

**Comment by weiyouren** [comment]
肯定允许啊，我最近在弄室内航位推算法研究，看到你这计步功能，提醒我，android已经有硬件计步了，所以试试，结果不工作，蛋疼

**Comment by linglongxin24** [comment]
华为的系统自带的管家，会默认锁屏清理应用，麻烦你把那个在里面设置成白名单，这样才可以的？

**Comment by weiyouren** [comment]
![screenshot_2016-10-24-10-00-12](https://cloud.githubusercontent.com/assets/3372167/19631586/ff0daa82-99d0-11e6-96c5-01c1bd6a4b69.png)

**Comment by linglongxin24** [comment]
你把app杀死，然后重启，装兜里出外面走几步，步数不变吗？

**Comment by weiyouren** [comment]
我换了台魅族手机可以了。但计步结果还是有误差的，哈哈哈，感谢你的代码和帮助

**Comment by linglongxin24** [comment]
这个都是获取的系统计歩返回的步数，由于我身边没有你这个机型，后面找到了我测试下
