### ISSUE TITLE
实现的很不错，不过还是有几个问题想请教

### ISSUE THREAD

**Issue by GuaiYiHu** [linglongxin24/DylanStepCount#12]
这个里面的services似乎都作废了呢，不知道是否还要保留呢== 
https://github.com/linglongxin24/DylanStepCount/tree/master/app/src/main/java/cn/bluemobi/dylan/step/pedometer
计步算法有待优化。。。疯狂摇晃手机也会起到计步的效果。。。这样就可以作弊啊
如上提到的计步算法应该是在这里的，不过看项目虽然不用了但是似乎还是保留在里面
https://github.com/bagilevi/android-pedometer

**Comment by linglongxin24** [comment]
那个确实是不用了，我后面会删除掉
