### ISSUE TITLE
你好，朋友，你使用我的算法没有问题，但是你说这个是原创就有点过分了，请你在你的项目里和文章中注明出处，谢谢！http://www.jianshu.com/p/5d57f7fd84fa

### ISSUE THREAD

**Issue by xfmax** [linglongxin24/DylanStepCount#14]
你好，朋友，你使用我的算法没有问题，但是你说这个是原创就有点过分了，请你在你的项目里和文章中注明出处，谢谢！http://www.jianshu.com/p/5d57f7fd84fa

**Comment by linglongxin24** [comment]
非常抱歉，原文已加出处！

**Comment by GunCc** [comment]
你好你这个文章我是第一次看的，所以不存在我使用了你的算法。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DylanAndroid"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 下午3:27
收件人:&nbsp;"linglongxin24/DylanStepCount"<DylanStepCount@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [linglongxin24/DylanStepCount] 你好，朋友，你使用我的算法没有问题，但是你说这个是原创就有点过分了，请你在你的项目里和文章中注明出处，谢谢！http://www.jianshu.com/p/5d57f7fd84fa (#14)





 
Closed #14.
