### ISSUE TITLE
好像不支持加速度传感器

### ISSUE THREAD

**Issue by tianshaokai** [linglongxin24/DylanStepCount#4]
我的测试手机是小米2s

**Comment by linglongxin24** [comment]
是的，需要硬件支持计步，也就是由计步传感器才可以的。对于硬件不支持的，本人正在研究中...

**Comment by tianshaokai** [comment]
对了 你的记步程序 支持用户吗，比如我登录一个用户可以记录步数，如果换个用户 步数就从 0 开始

**Comment by tianshaokai** [comment]
希望作者增加一个 查看 卡路里和 里程的 功能

**Comment by linglongxin24** [comment]
那个每天的步数是存在数据库当中的，所以可以支持多用户的，对数据库增加一个字段就可以了。

**Comment by linglongxin24** [comment]
正在考虑后续功能的扩展...

**Comment by tianshaokai** [comment]
1测试小米4 android 6.0.1 mui 7.5 测试后发现 不记录步数
2 增加一个字段 ，获取的步数 是从芯片里获取的吧，如果第一个用户走了1000 步，我换个用户 还是从芯片里获取数据 不也是1000 步了啊

**Comment by linglongxin24** [comment]
1.小米4可能不支持计步，
2.步数是从芯片获取的，但是经过处理的，最终一数据库为准，不会存在你说那个情况。

**Comment by tianshaokai** [comment]
1  我想问一下 该怎么处理 一下这个问题呢，我最近是和春雨医生合作的但是现在就有这个问题，不知道怎么做了

**Comment by linglongxin24** [comment]
你是谁问小米4不支持的问题还是切换用户步数的问题？

**Comment by linglongxin24** [comment]
？？？

**Comment by tianshaokai** [comment]
主要是切换用户步数的问题，怎么处理一下呢？？

**Comment by linglongxin24** [comment]
这个好办，1.在StepData这个中添加一个用的字段
![image](https://cloud.githubusercontent.com/assets/9549188/20254372/e4c9e628-aa6e-11e6-9fa4-a4f9e9363da7.png)
2.在StepService中初始化数据的时候用当天的时间和添加个用户字段去查询
![image](https://cloud.githubusercontent.com/assets/9549188/20254419/45582b3a-aa6f-11e6-82f1-1faa594045f2.png)

**Comment by linglongxin24** [comment]
这样的话每个用户的数据都是单独的，肯定不会出现问题的。

**Comment by tianshaokai** [comment]
我想问一下啊，我存入数据的时候 是不是获取的芯片里的数据 呢？？如果是获取芯片里的数据，插入到表中的时候 怎么判断  这些 步数 是 不是 当前用户的数据呢？？ 我现在就是 想不明白怎么解决

**Comment by linglongxin24** [comment]
你插入的时候肯定要根据用户id去插入的啊，一个手机只能登陆一个用户，这个数据肯定是当前登陆用户的啊！

**Comment by tianshaokai** [comment]
我假设换个用户呢？？我就想不明白怎么处理了

**Comment by linglongxin24** [comment]
换个用户数据就从新初始化啊！

**Comment by linglongxin24** [comment]
明白没有？

**Comment by tianshaokai** [comment]
从新初始化一个数据库对吧，那获取芯片的数据都是上个用户的啊

**Comment by linglongxin24** [comment]
![image](https://cloud.githubusercontent.com/assets/9549188/20254811/b83b477e-aa72-11e6-89ec-5f0e5d487169.png)

**Comment by linglongxin24** [comment]
不是的，初始化是从数据库中拿数据的，不是从手机芯片拿的

**Comment by tianshaokai** [comment]
我明白查询数据的时候 按照日期和 用户id 查询，，我只是不明白 插入数据的时候 怎么判断 芯片的数据 多少步数是这个用户的，多少步数是那个用户的，因为 芯片里的数据 都在一直增加

**Comment by linglongxin24** [comment]
这个，就看你再插入数据的时候是哪个用户在登陆啊？

**Comment by linglongxin24** [comment]
明白了么？

**Comment by linglongxin24** [comment]
这么给你说吧，app只有在运行或者说在后台运行，只要service不死，就可以计歩，而计歩只有app打开才开始计歩，app关闭，就不计歩了。明白了么？

**Comment by tianshaokai** [comment]
1. 这些我都明白
2. 切换用户肯定是数据库不一样
3. 插入数据肯定是往当前登录人的数据库插入
3. 查询肯定是根据日期和用户查询

以上这些我都明白
只是下边的我不理解
1.  记步芯片的数据一直在增加
2. 我假设用 A用户走了1000 步，插入数据库的数据是 1000 步
3. 我假设 用同一个手机 登录用户B， 那么B用户在获取步数的时候 也能获取 刚才 A 用户的 1000步的

**Comment by linglongxin24** [comment]
我的步数，不是芯片返回多少我就记多少，我是记录从我启动app以后的增量，要不然谁也没办法知道没用app的时候数据到底属于谁的，这本来就是个伪命题。比如微信，你到了晚上，换个账号，你觉得这个数据属于谁的？这根本就是个无厘头的问题。多以没办法考虑的。

**Comment by tianshaokai** [comment]
嗯嗯 其实我一直都是在问这个问题的解决思路，谢谢你

**Comment by linglongxin24** [comment]
没事，这种问题，没有办法解决的，只有我们在程序对步数做处理，要不然我们就不用去建立数据库了，这样更简单，非要区分用户，那就只能在每天第一次打开app的时候开始从零计歩，这样合情合理。
