### ISSUE TITLE
 同一台手机。两个应用。为啥步数不一样。

### ISSUE THREAD

**Issue by z2045217** [linglongxin24/DylanStepCount#5]
程序在后台。有没有service被kill的可能。kill了能不能在自动链接上。

**Comment by linglongxin24** [comment]
1.应用启动了才会计歩，关闭或退出后停止计歩
2.service有可能被杀死，这个暂时没有做自动进程维护。

**Comment by z2045217** [comment]
好吧。那我看看。能不能加入吧。应为程序service肯定有可能会被kill的。
